# Generated by Django 5.1 on 2025-06-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Títilo')),
                ('genero', models.CharField(max_length=60, null=True, verbose_name='Gênero')),
                ('data_publicacao', models.DateField(null=True, verbose_name='Dada de publicação')),
                ('numero_paginas', models.PositiveIntegerField(null=True, verbose_name='Páginas')),
                ('estoque', models.PositiveIntegerField(null=True, verbose_name='Quantidade')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço')),
            ],
        ),
    ]
