# Generated by Django 5.1 on 2025-06-27 18:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='data_publicacao',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='estoque',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='numero_paginas',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='preco',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='titulo',
        ),
        migrations.AddField(
            model_name='livro',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='livro',
            name='profileName',
            field=models.CharField(max_length=100, null=True, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='livro',
            name='review_helpfulness',
            field=models.CharField(max_length=10, null=True, verbose_name='Utilidade'),
        ),
        migrations.AddField(
            model_name='livro',
            name='review_score',
            field=models.CharField(max_length=10, null=True, verbose_name='Avaliação'),
        ),
        migrations.AddField(
            model_name='livro',
            name='review_summary',
            field=models.CharField(max_length=500, null=True, verbose_name='Resumo do review'),
        ),
        migrations.AddField(
            model_name='livro',
            name='review_text',
            field=models.CharField(max_length=1000, null=True, verbose_name='Texto do review'),
        ),
        migrations.AddField(
            model_name='livro',
            name='review_time',
            field=models.CharField(max_length=50, null=True, verbose_name='Hora do review'),
        ),
        migrations.AddField(
            model_name='livro',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Título'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livro',
            name='user_id',
            field=models.CharField(max_length=100, null=True, verbose_name='ID Usuário'),
        ),
    ]
