# Generated by Django 5.1 on 2025-06-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('idade', models.PositiveIntegerField(max_length=3, verbose_name='Idade')),
            ],
        ),
        migrations.AddField(
            model_name='livro',
            name='autor',
            field=models.CharField(max_length=100, null=True, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='data_publicacao',
            field=models.DateField(null=True, verbose_name='Data de publicação'),
        ),
    ]
